### ISSUE TITLE
Build Error installing on OSX

### ISSUE THREAD

**Issue by johnsgill3** [rubenv/zipper#12]
Trying to install zipper on an OSX machine getting the following build error.

``` shell
$ npm install zipper
```

Output:

```
In file included from ../src/_zipper.cc:9:
../src/zipper.hpp:25:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> New(const Arguments &args);
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/johngill/.node-gyp/5.9.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/_zipper.cc:9:
../src/zipper.hpp:28:40: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> addFile(const Arguments& args);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/johngill/.node-gyp/5.9.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/_zipper.cc:9:
../src/zipper.hpp:29:26: error: unknown type name 'uv_work_t'
    static void _AddFile(uv_work_t *req);
                         ^
../src/zipper.hpp:30:31: error: unknown type name 'uv_work_t'
    static void _AfterAddFile(uv_work_t *req);
                              ^
../src/_zipper.cc:22:25: error: no member named 'NewSymbol' in 'v8::String'
    target->Set(String::NewSymbol("version"), String::New("0.0.1"));
                ~~~~~~~~^
../src/_zipper.cc:22:55: error: no member named 'New' in 'v8::String'
    target->Set(String::NewSymbol("version"), String::New("0.0.1"));
                                              ~~~~~~~~^
../src/_zipper.cc:25:42: error: too few arguments to function call, single argument 'isolate' was not specified
    Local<Object> versions = Object::New();
                             ~~~~~~~~~~~ ^
/Users/johngill/.node-gyp/5.9.0/include/node/v8.h:2930:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
../src/_zipper.cc:26:27: error: no member named 'NewSymbol' in 'v8::String'
    versions->Set(String::NewSymbol("node"), String::New(NODE_VERSION+1));
                  ~~~~~~~~^
../src/_zipper.cc:26:54: error: no member named 'New' in 'v8::String'
    versions->Set(String::NewSymbol("node"), String::New(NODE_VERSION+1));
                                             ~~~~~~~~^
../src/_zipper.cc:27:27: error: no member named 'NewSymbol' in 'v8::String'
    versions->Set(String::NewSymbol("v8"), String::New(V8::GetVersion()));
                  ~~~~~~~~^
../src/_zipper.cc:27:52: error: no member named 'New' in 'v8::String'
    versions->Set(String::NewSymbol("v8"), String::New(V8::GetVersion()));
                                           ~~~~~~~~^
../src/_zipper.cc:28:25: error: no member named 'NewSymbol' in 'v8::String'
    target->Set(String::NewSymbol("versions"), versions);
                ~~~~~~~~^
12 errors generated.
make[1]: *** [Release/obj.target/zipper/src/_zipper.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/Cellar/node/5.9.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/johngill/git/wedding-site/node_modules/zipper
gyp ERR! node -v v5.9.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
make: *** [lib/_zipper.node] Error 1
npm WARN wedding-site@0.0.1 No repository field.
npm WARN wedding-site@0.0.1 No license field.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.9.0/bin/node" "/usr/local/bin/npm" "install" "zipper"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! zipper@0.3.0 install: `make all`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the zipper@0.3.0 install script 'make all'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zipper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make all
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zipper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zipper
npm ERR! There is likely additional logging output above.
```

**Comment by leo-santanna** [comment]
I've got the same error trying to install the package on the latest OS X 10.11.5. Could you shine some light on our issue, please?

Thanks in advance!
